var group__bmi08ag =
[
    [ "Gyro Initialization", "group__bmi08a_api_init.html", "group__bmi08a_api_init" ],
    [ "Accel Upload Config File", "group__bmi08a_api_config.html", "group__bmi08a_api_config" ],
    [ "Upload Feature Config File", "group__bmi08a_api_f_config.html", "group__bmi08a_api_f_config" ],
    [ "Accel Data", "group__bmi08a_api_regs.html", "group__bmi08a_api_regs" ],
    [ "Accel Error status", "group__bmi08a_api_error_status.html", "group__bmi08a_api_error_status" ],
    [ "Accel status", "group__bmi08a_apistatus.html", "group__bmi08a_apistatus" ],
    [ "Accel Soft reset", "group__bmi08a_api_softreset.html", "group__bmi08a_api_softreset" ],
    [ "Read accel configurations", "group__bmi08a_api_conf.html", "group__bmi08a_api_conf" ],
    [ "Accel power mode", "group__bmi08a_api_powermode.html", "group__bmi08a_api_powermode" ],
    [ "Accel Data", "group__bmi08a_api_data.html", "group__bmi08a_api_data" ],
    [ "Accel Interrupt Config", "group__bmi08a_api_int_conf.html", "group__bmi08a_api_int_conf" ],
    [ "Accel Temperature", "group__bmi08a_api_accel_temp.html", "group__bmi08a_api_accel_temp" ],
    [ "Accel sensor time", "group__bmi08a_apiaccelsensortime.html", "group__bmi08a_apiaccelsensortime" ],
    [ "Data Synchronization", "group__bmi08a_api_sync.html", "group__bmi08a_api_sync" ],
    [ "Sync Data", "group__bmi08a_api_sync_data.html", "group__bmi08a_api_sync_data" ],
    [ "interrupt", "group__bmi08a_api_int.html", "group__bmi08a_api_int" ],
    [ "Gyro Initialization", "group__bmi08g_api_init.html", "group__bmi08g_api_init" ],
    [ "Gyro Data", "group__bmi08g_api_regs.html", "group__bmi08g_api_regs" ],
    [ "gyro Soft reset", "group__bmi08g_api_softreset.html", "group__bmi08g_api_softreset" ],
    [ "Read gyro configurations", "group__bmi08g_api_conf.html", "group__bmi08g_api_conf" ],
    [ "Gyro power mode", "group__bmi08g_api_powermode.html", "group__bmi08g_api_powermode" ],
    [ "Gyro data", "group__bmi08g_api_data.html", "group__bmi08g_api_data" ],
    [ "Gyro interrupt config", "group__bmi08g_api_intconfig.html", "group__bmi08g_api_intconfig" ],
    [ "Gyro self test", "group__bmi08g_api_selftest.html", "group__bmi08g_api_selftest" ],
    [ "FIFO", "group__bmi08g_api_f_i_f_o.html", "group__bmi08g_api_f_i_f_o" ],
    [ "FIFO operations", "group__bmi08a_api_fifo.html", "group__bmi08a_api_fifo" ],
    [ "Extract accel frames from FIFO", "group__bmi08a_api_extract_accel.html", "group__bmi08a_api_extract_accel" ],
    [ "Accel FIFO down sampling", "group__bmi08a_api_f_i_f_o_down.html", "group__bmi08a_api_f_i_f_o_down" ]
];